site_name: EBI Cloud Portal - Malware applicatio
pages:
- Home: index.md
- Terraform - Google Cloud: gcp-terraform.md
- API testing: api-testing.md
- Mkdocs Documentation: mkdocs.md
theme: readthedocs
